version: '3.8'

services:
  # 1. DJANGO UYGULAMASI
  web:
    build: .
    command: gunicorn padel_community.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # 2. POSTGRESQL VERİTABANI
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=padel_local_db
      - POSTGRES_USER=padel_user
      - POSTGRES_PASSWORD=padel_password

volumes:
  postgres_data: