"""
Django settings for padel_community project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-)d8ce(xmnq+n%08ff#w&j5uqu8xg18sjwxe=u$2$vp$v%wtark")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    'courtmax-padel-mate.onrender.com',
    'courtmaxpadel.com',
    'www.courtmaxpadel.com',
    'localhost',
    '127.0.0.1'
]

# 2. Form güvenliği
CSRF_TRUSTED_ORIGINS = [
    'https://courtmax-padel-mate.onrender.com',
    'https://courtmaxpadel.com',
    'https://www.courtmaxpadel.com',
]

# Application definition

INSTALLED_APPS = [
    'players.apps.PlayersConfig',

    'cloudinary_storage', # En başta olmalı
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # WhiteNoise için gerekli

    'cloudinary',
    'rest_framework',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise Middleware (En üstlerde olmalı)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "padel_community.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'players.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = "padel_community.wsgi.application"


# Database
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://padel_mate_user:8WkbvDFbSmXGsCn2e2BCEC9ZR82PSVJQ@dpg-d4eq99rgk3sc73btca50-a.frankfurt-postgres.render.com/padel_mate',
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator" },
    { "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator" },
    { "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator" },
    { "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator" },
]


# Internationalization
LANGUAGE_CODE = "tr-tr"
TIME_ZONE = "Europe/Istanbul"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'

# --- DOSYA DEPOLAMA AYARLARI (KRİTİK DÜZELTME) ---

# 1. Yeni Yöntem (STORAGES)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 2. Eski Yöntem (Uyumluluk İçin ŞART - Hata Sebebi Buydu)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login/Logout Yönlendirmeleri
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# --- CLOUDINARY API AYARLARI ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'divljychy'), 
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '372999294198912'), 
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'yUt4kD31eX_0Hu516ATRONG3qBA'),
    'SECURE': True,
    'MEDIA_TAG': 'media',
}

# --- E-POSTA AYARLARI ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'courtmaxpm@gmail.com' 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'wgtl soqn xpxz ybyh')
DEFAULT_FROM_EMAIL = 'Courtmax Padel Mate <noreply@courtmax.com>'

LOGIN_URL = 'login'
PASSWORD_CHANGE_REDIRECT_URL = 'home'

SESSION_COOKIE_AGE = 1000
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
CSRF_USE_SESSIONS = True