"""
Django settings for padel_community project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)d8ce(xmnq+n%08ff#w&j5uqu8xg18sjwxe=u$2$vp$v%wtark"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'courtmax-padel-mate.onrender.com',  # Render adresi
    'courtmaxpadel.com',                 # Yeni domain (kısa)
    'www.courtmaxpadel.com',             # Yeni domain (uzun)
    'localhost',
    '127.0.0.1'
]

# 2. Form güvenliği (Giriş yapabilmek için ŞART)
# Buraya domainlerin başında 'https://' olacak şekilde yazmalısın.
CSRF_TRUSTED_ORIGINS = [
    'https://courtmax-padel-mate.onrender.com',
    'https://courtmaxpadel.com',
    'https://www.courtmaxpadel.com',
]

# Application definition

INSTALLED_APPS = [

     'players.apps.PlayersConfig',

    # Cloudinary (En başta)
    'cloudinary_storage',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Diğerleri
    'cloudinary',
    'rest_framework',
    
    # SİZİN UYGULAMANIZ (Sadece bu olmalı)
    
    
    # DİKKAT: Burada 'accounts' varsa SİLİN!

]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise Middleware (CSS dosyaları için)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "padel_community.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "padel_community.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Render'daki veritabanı bağlantı adresi
        default='postgresql://padel_mate_user:8WkbvDFbSmXGsCn2e2BCEC9ZR82PSVJQ@dpg-d4eq99rgk3sc73btca50-a.frankfurt-postgres.render.com/padel_mate',
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- YENİ EKLENEN: MEDIA URL ---
MEDIA_URL = '/media/'


# --- DOSYA DEPOLAMA AYARLARI ---

# 1. Yeni Yöntem (STORAGES)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 2. Eski Yöntem
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login/Logout Yönlendirmeleri
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Güvenlik (CSRF)
CSRF_TRUSTED_ORIGINS = [
    'https://courtmax-padel-mate.onrender.com',
]

# --- CLOUDINARY API AYARLARI ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'divljychy'), 
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '372999294198912'), 
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'yUt4kD31eX_0Hu516ATRONG3qBA'),
    'SECURE': True,
    'MEDIA_TAG': 'media',
}

# --- E-POSTA AYARLARI (Şifre Sıfırlama İçin) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Gmail Adresiniz (Gönderen Kişi)
EMAIL_HOST_USER = 'courtmaxpm@gmail.com'  # <-- BURAYA KENDİ GMAIL ADRESİNİZİ YAZIN

# Gmail Uygulama Şifresi (Verdiğiniz şifre buraya eklendi)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'wgtl soqn xpxz ybyh')

DEFAULT_FROM_EMAIL = 'Courtmax Padel Mate <noreply@courtmax.com>'

LOGIN_URL = 'login'  # login view'unuzun URL name'i
PASSWORD_CHANGE_REDIRECT_URL = 'home'  # Şifre değişim sonrası yönlendirme