# Generated by Django 5.2.8 on 2025-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
