# Generated by Django 5.2.8 on 2025-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.CharField(choices=[('0-1.0 Beginner', '🟩 0 – 1.0: Tam Başlangıç (Beginner)'), ('1.5 Novice', '🟩 1.5: Yeni Öğrenen (Novice)'), ('2.0-2.5 Improver', '🟨 2.0 – 2.5: Gelişen Oyuncu (Improver)'), ('3.0 Intermediate', '🟨 3.0: Orta Seviye (Intermediate)'), ('3.5 Upper Intermediate', '🟨 3.5: Orta-Üst Seviye (Upper Intermediate)'), ('4.0 Advanced', '🟧 4.0: İyi Seviye (Advanced)'), ('4.5 High Advanced', '🟧 4.5: İleri (High Advanced)'), ('5.0 Semi Pro', '🟥 5.0: Yarı-Pro (Semi Pro)'), ('5.5-6.0 Pro', '🟥 5.5 – 6.0: Pro (Professional)'), ('6.5-7.0 Elite', '🟥 6.5 – 7.0: Elit / Dünya Sınıfı')], default='0-1.0 Beginner', max_length=100),
        ),
    ]
