# Generated by Django 5.2.8 on 2025-11-20 05:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
