# Generated by Django 5.2.8 on 2025-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set1_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set1_team2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_team2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_team1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_team2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
