# Generated by Django 5.2.8 on 2025-12-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_match_set1_team1_match_set1_team2_match_set2_team1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kort Adı')),
                ('city', models.CharField(default='İzmir', max_length=100, verbose_name='Şehir')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.court', verbose_name='Oynanan Kort'),
        ),
    ]
