# Generated by Django 5.2.8 on 2025-12-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0006_court_match_court"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("0-1.0 Beginner", "🟩 0 – 1.0: Tam Başlangıç (Beginner)"),
                    ("1.5 Novice", "🟩 1.5: Yeni Öğrenen (Novice)"),
                    ("2.0-2.5 Improver", "🟨 2.0 – 2.5: Gelişen Oyuncu (Improver)"),
                    ("3.0 Intermediate", "🟨 3.0: Orta Seviye (Intermediate)"),
                    ("3.5 Upper Int", "🟨 3.5: Orta-Üst Seviye (Upper Int)"),
                    ("4.0 Advanced", "🟧 4.0: İyi Seviye (Advanced)"),
                    ("4.5 High Advanced", "🟧 4.5: İleri (High Advanced)"),
                    ("5.0 Semi Pro", "🟥 5.0: Yarı-Pro (Semi Pro)"),
                    ("5.5-6.0 Pro", "🟥 5.5 – 6.0: Pro (Professional)"),
                    ("6.5-7.0 Elite", "🟥 6.5 – 7.0: Elit / Dünya Sınıfı"),
                ],
                default="0-1.0 Beginner",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="MatchLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("partner", "🤝 Takım Arkadaşı Arıyorum"),
                            ("opponents", "⚔️ Rakip Arıyorum"),
                            ("both", "🎯 Her İkisi de Olur"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(verbose_name="Tercih Edilen Tarih"),
                ),
                (
                    "preferred_time_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Başlangıç Saati"
                    ),
                ),
                (
                    "preferred_time_end",
                    models.TimeField(blank=True, null=True, verbose_name="Bitiş Saati"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                (
                    "skill_level_min",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Min. Seviye"
                    ),
                ),
                (
                    "skill_level_max",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Maks. Seviye"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Not/Açıklama"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("matched", "Eşleşti"),
                            ("expired", "Süresi Doldu"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(verbose_name="Son Geçerlilik")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_lookups",
                        to="players.player",
                    ),
                ),
                (
                    "preferred_court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.court",
                        verbose_name="Tercih Edilen Kort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maç Arama İlanı",
                "verbose_name_plural": "Maç Arama İlanları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchLookupResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, max_length=300, verbose_name="Mesaj"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("accepted", "Kabul Edildi"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lookup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="players.matchlookup",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookup_responses",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("lookup", "responder")},
            },
        ),
    ]
