# Generated by Django 5.2.8 on 2025-12-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0007_alter_player_skill_level_matchlookup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.match",
            ),
        ),
    ]
